Display lift log rows
Yakimych/lift-log-reason-react pull request #3
Opened 2019-01-10 23:33 UTC by MargaretKrutikova

2019-01-11 00:03 UTC, Yakimych requested changes

2019-01-11 00:03 UTC, Yakimych commented on src/AppRoot.re
> +              dateFormat="YYYY-MM-DD"
Can we use the same dateFormat in the list?

2019-01-11 00:03 UTC, Yakimych commented on src/LiftLogContainer.re
> +        <h6 className="col"> {"Date" |> ReasonReact.string} </h6>
Here.

2019-01-11 00:03 UTC, Yakimych commented on src/LiftLogContainer.re
> +              <LiftRow entry=logEntry key={string_of_int(index)} />
Neat - using an object instead of spreading. Feels more natural to do it this way here than in JS/TS.

2019-01-11 00:03 UTC, Yakimych commented on src/Utils.re
> +  sets |> List.for_all(s => s.reps === List.hd(sets).reps);
What happens when the list is empty? It probably doesn't matter, but still interesting - true or false?

2019-01-11 00:03 UTC, Yakimych commented on src/Utils.re
> +  };
Missing trailing linebreak.

2019-01-11 00:03 UTC, Yakimych commented on src/Utils.re
> +    (sets |> List.length |> string_of_int)
I suggest we break it up into smaller functions - e.g. `formatSetsReps` and `formatCustomSets` as we do in the TS version. Also interesting whether it crashes with an empty array (`List.hd` does). I guess it depends on whether `allRepsAreEqual` returns true or false for an empty list.

2019-01-11 00:03 UTC, Yakimych commented on src/Utils.re
> +           | other => other ++ "-" ++ string_of_int(value)
Why is this called `other`?

2019-01-11 00:03 UTC, Yakimych commented on src/AppRoot.re
> +      <LiftLogContainer entries={self.state.liftLogState.logEntries} />
List of entries should come after `AddEntry`.

2019-01-11 00:15 UTC, Yakimych commented on src/Utils.re
> +    (sets |> List.length |> string_of_int)
Then we can use `?` `:` syntax instead of if/else.

2019-01-12 13:11 UTC, MargaretKrutikova commented on src/Utils.re
> +  sets |> List.for_all(s => s.reps === List.hd(sets).reps);
I checked for empty list in `formatSets`.

2019-01-12 13:18 UTC, Yakimych approved these changes

2019-01-12 13:18 UTC, merged